### ISSUE TITLE
ERROR:asyncio:Unclosed client session

### ISSUE THREAD

**Issue by andycoates** [tomplus/kubernetes_asyncio#103]
Hi,

If I use `example4.py` but don't see any changes (or set `timeout_seconds=10` to force an early close) I see exceptions/errors after the initial list of events:

```
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x109d3ba90>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x109d37550>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x109d667c0>, 10.727993494)]']
connector: <aiohttp.connector.TCPConnector object at 0x109d37590>
```
I'm using python 3.7.5 with:
```
kubernetes==11.0.0
kubernetes-asyncio==11.2.0
```

I saw a recent issue where I think the context manager was changed to `close()` in 11.2.0, but it seems `aiohttp.ClientSession` isn't actually closing properly?

**Comment by tomplus** [comment]
Hi @andycoates 

Thanks for reporting this issue.

I dig into it and I've found:

1. example4 should use the context manager to close sessions properly
   ```
    async with ApiClient() as api:
        v1 = client.CoreV1Api(api)
        async with watch.Watch().stream(v1.list_pod_for_all_namespaces,
                                        timeout_seconds=10) as stream:
            async for event in stream:
                evt, obj = event['type'], event['object']
                print("{} pod {} in NS {}".format(evt, obj.metadata.name, obj.metadata.namespace))

   ```

2. watch() creates instance of the ApiClient but the instance is not closed and aiohttp reports one more warning.

I'll fix it in the next release.
