### ISSUE TITLE
close() in `Watch.stream()` not awaited

### ISSUE THREAD

**Issue by WoLpH** [tomplus/kubernetes_asyncio#109]
It seems there's an `await` missing in front of the `close()` here: 

https://github.com/tomplus/kubernetes_asyncio/blob/d6ec797a61d8bfad89549c3166d6ee78bed884e6/kubernetes_asyncio/watch/watch.py#L190

**Comment by tomplus** [comment]
Thanks for spotting this. I'm going to remove this instruction in the next release (it's redundant, aexit calls close()).
