### ISSUE TITLE
Asyncio support

### ISSUE THREAD

**Issue by sonicaj** [tomplus/kubernetes_asyncio#111]
Thank you @tomplus for working on this project. I was going through python clients for k8s and this suits my needs perfectly. However I wanted to ask how is this project maintained and is it safe to assume that we should expect upstream support ? ( it would be great btw if upstream k8s made this official as well )

My case is that we would like to use it but would also like to know if we should be expecting some support from upstream ( we are willing to help as well as much as we can do ).

Looking forward to hearing from you, thank you.

**Comment by tomplus** [comment]
Hi @sonicaj I'm happy to hear that the library suits your needs. It’s maintained. It isn't official, but both libraries (this and the official) are generated by the Openapi-generator which has a huge community. I also backport bugfixes between libraries in both directions, stick to the official release number etc. to make it similar.

I encourage you to use it in your project. :+1:

**Comment by sonicaj** [comment]
Thank you @tomplus for reaching back and for reassuring. We will go ahead then ; )
