### ISSUE TITLE
Unsupported Media Type (HTTP 415) when patching custom resources

### ISSUE THREAD

**Issue by linkous8** [tomplus/kubernetes_asyncio#125]
Same issue as documented here: https://github.com/kubernetes-client/python/issues/866

See solution here: https://github.com/palnabarun/python/commit/f1cc695a6cd83234f6ab3ab3cdb2807214d2e328

Would you review/merge a PR if I were to submit one?

**Comment by tomplus** [comment]
Hi @linkous8 It's already reported here: #68 I'm working on it now.

**Comment by linkous8** [comment]
whoops, guess I didn't scroll far enough :+1:
