### ISSUE TITLE
Implement create_from_dict

### ISSUE THREAD

**Issue by ChriZiegler** [tomplus/kubernetes_asyncio#142]
The main kubernetes client has a useful function in utils called [`create_from_dict`](https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/create_from_yaml.py). This function is absent in kubernetes_asyncio, but would be very useful, particularly in the case where you want to create a resource from yaml template and change some values in it, without needing to save the altered yaml to a file.

Alternatively, exposing `create_from_yaml_single_item` officially in the `__init__.py` of `utils` would achieve a similar result

**Comment by tomplus** [comment]
@ChriZiegler It should be the same as in the main client. I'll fix it over the weekend. Thanks.

**Comment by ChriZiegler** [comment]
@tomplus Thank you so much! Do you know when this will be available on PyPi?

**Comment by tomplus** [comment]
Sorry for the delay. It's already released.
