### ISSUE TITLE
Update to kubernetes api version 1.18

### ISSUE THREAD

**Issue by felixhuettner** [tomplus/kubernetes_asyncio#155]
Hi everyone,

The upstream kubernetes python project now supports kubernetes 1.18. It would be great if `kubernetes_asyncio` could support that as well.

If its just regenerating the client with a new k8s version then i could do that as well, but i was not sure about that.

Best Regards

**Comment by tomplus** [comment]
Absolutely! The library has to be updated. Usually it's not complicated but I haven't done it for a long time and I'm afraid that some  issues may appear. I'll do it soon.

**Comment by tomplus** [comment]
I've just released new version of the library - v18.20.0, which is based on K8s 1.8. Enjoy ;)

**Comment by felixhuettner** [comment]
Thank you very much :)
