### ISSUE TITLE
Update to kubernetes api version 1.21

### ISSUE THREAD

**Issue by felixhuettner** [tomplus/kubernetes_asyncio#171]
Hi everyone,

The kubernetes python project now supports kubernetes 1.19, 1.20, 1.21. It would be great if kubernetes_asyncio could support that as well.

Thank you

**Comment by tomplus** [comment]
Version 19.15.0 with support for K8s 1.19.15 has been released.

**Comment by devlounge** [comment]
Any update on this?

**Comment by tomplus** [comment]
@devlounge which version do you need most?

**Comment by devlounge** [comment]
> @devlounge which version do you need most?

1.21.9 ideally

**Comment by tomplus** [comment]
Two versions have been released - v20.13.0 (K8s 1.20.13), v21.7.0 (K8s 1.21.7) - the same values as in the official Python library. 

I can generate 1.21.9 but i don't see any API changes between 1.21.7 vs 1.21.9. Could you check if v21.7.0 is enough in your case.

**Comment by devlounge** [comment]
> Two versions have been released - v20.13.0 (K8s 1.20.13), v21.7.0 (K8s 1.21.7) - the same values as in the official Python library.
> 
> I can generate 1.21.9 but i don't see any API changes between 1.21.7 vs 1.21.9. Could you check if v21.7.0 is enough in your case.

No that’s perfect as long as it’s 1.21.x
Thanks!

**Comment by dcecile** [comment]
Kubernetes v1.23 includes new official HPA APIs: https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/#horizontalpodautoscaler-v2-graduates-to-ga

(HPA v2beta1 is being removed in [v1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125), and v2beta2 is being removed in [v1.26](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126).)

**Comment by tomplus** [comment]
I've just released version 23.6.0 which is based on API K8s 1.23.6.

**Comment by dcecile** [comment]
Thanks! :pray:

**Comment by tomplus** [comment]
The latest released version is the same as official client - v24.2.0.
