### ISSUE TITLE
watches still deserialize with _preload_content=False

### ISSUE THREAD

**Issue by athornton** [tomplus/kubernetes_asyncio#176]
That appears to be a consequence of   https://github.com/tomplus/kubernetes_asyncio/blob/f2b270df403df49798de70b93b84abd21d1db5f9/kubernetes_asyncio/watch/watch.py#L204

I'm aware that I can get the dict_representation from raw_object, but my concern is performance rather than ease of representation.  

The context is: I'm trying to replace the K8s API implementation in JupyterHub's Kubespawner with kubespawner_asyncio, and there's this issue in kubespawner, related to high load caused by deserialization in busy Kubernetes clusters:

https://github.com/jupyterhub/kubespawner/issues/423

That was addressed in the stock KubeSpawner by:

https://github.com/jupyterhub/kubespawner/pull/424 (which uses _preload_content=False to speed things up)

I haven't yet dug into the kubernetes_asyncio code to see how hard it would be to skip the deserialization if _preload_content is False and return the dict in both the object and raw_object fields, but that's what I ideally would like to have happen.

**Comment by tomplus** [comment]
It looks like KubeSpawner does a little hack to skip the deserialization - it wraps methods using `partial()` so Kubernetes client cannot detect the type of object and returns only raw response. Kubernetes-asyncio is not ready for such trick and raises an exception, as you noticed [here](https://github.com/lsst-sqre/kubespawner/pull/2/files#diff-23f3b56e5e9b6c8e67401eab22ce6a30ccfdfe9a2979bea23d33505d74515efdR331). I'll fix it soon.

**Comment by tomplus** [comment]
I've just released v19.15.1 with the fix.
