### ISSUE TITLE
Regression via recent code regeneration

### ISSUE THREAD

**Issue by consideRatio** [tomplus/kubernetes_asyncio#183]
It seems that #181 that re-generated the python code base reverted #123.

#123 seems to be a fix to the generated code base, and was therefore reverted by #181.

https://github.com/tomplus/kubernetes_asyncio/blob/da1e3172acd098e5feb47193bd9d73428078b61a/kubernetes_asyncio/client/api_client.py#L191

**Comment by tomplus** [comment]
Sorry, my bad. I'm fixing it now.

**Comment by tomplus** [comment]
Fixed in v21.7.1.

**Comment by consideRatio** [comment]
@tomplus :heart: :tada: thank you for your work with this project!
