### ISSUE TITLE
Request for additional details in CONTRIBUTING.md

### ISSUE THREAD

**Issue by consideRatio** [tomplus/kubernetes_asyncio#189]
Before I observed a regression in v21 (https://github.com/tomplus/kubernetes_asyncio/issues/183) and were happy to see this didn't happen in v22 as well, but it left me curious to understand more how this codebase works which would also help me and others contribute to it.

Practically, I wondered if CONTRIBUTING.md could be enhanced with some more details to provide understanding about  the code base's various parts. Some concrete things that I think could benefit from clarifications would be:
- what is purely generated code and what isn't?
- what adjustments have been made, and how have they been made technically?

  I'm thinking it could be: manual patches post-generation, automated post-generation patches, pre-generation configuration to influence the generation, etc.
  
---

Thanks you @tomplus for your work in this project! I'm very happy to see the v22 release and that releases are almost fully up to date with k8s releases!

**Comment by tomplus** [comment]
Thanks for your kind words.

I've updated the Contributing guide.

The generation process has to be fully automatic. No manual patches, I took shortcuts last time and we know how it's ended ;)

**Comment by consideRatio** [comment]
Thank you @tomplus!!
