### ISSUE TITLE
Allow for configurable heartbeat in WsApiClient request method

### ISSUE THREAD

**Issue by GlassOfWhiskey** [tomplus/kubernetes_asyncio#193]
When running long commands without intermediate output through the WsApiClient, the connection is closed after timeout.
To correct this error, a custom heartbeat parameter can be passed  to the `ws_connect` method of the `rest_client.pool_manager` attribute in the `request` method of the `WsApiClient` object (lines 80 and 94 of the `stream/ws_client.py` file). Something like:

```python
return await self.rest_client.pool_manager.ws_connect(url, headers=headers, heartbeat=heartbeat)
```

It would be useful to have a way to percolate a custom `Optional[float]` heartbeat value (default `None`) through the `WsApiClient` constructor, such that the user can configure it whenever needed.

**Comment by tomplus** [comment]
It sounds good to me. Are you going to add a pull-request with it?

**Comment by GlassOfWhiskey** [comment]
Hi @tomplus. Yes I have no problems in creating a PR.
I've read the Contribution guidelines but it is not clear to me how to proceed. The document says that I should sign a Contributor License Agreement as stated "above" but there is no "above" in the document. Plus, I don't know if I only have to submit the change or if I should also add some kind of no regression test somewhere.
BTW I will start making the main change and then I'll wait for your answer before submitting the PR.

**Comment by tomplus** [comment]
I've just updated the contribution guide.

Yes, please add tests. IMO unit-tests would be enough in this case, I guess e2e tests may be more complicated.

I'm looking forward to your PR.
