### ISSUE TITLE
Question: Way to Create New CRD?

### ISSUE THREAD

**Issue by paxbit** [tomplus/kubernetes_asyncio#200]
Hi,

I was looking at the docs as well as:
https://github.com/tomplus/kubernetes_asyncio/blob/master/kubernetes_asyncio/client/api/custom_objects_api.py 
and was wondering if kubernetes_asyncio supports creation of CustomResourceDefinitions. I can find the `V1CustomResourceDefinition` mapping class but the way I see it the corresponding API methods are missing. 

I can CRUD the concrete custom objects once the custom kind is there but I cannot seem to find a way to create the CRD itself. Is there a way?

Thanks!

paxbit

**Comment by paxbit** [comment]
Hi,

from the looks of it I think it will. Will try, thanks!

**Comment by tomplus** [comment]
I'm closing it now. Please feel free to reopen if needed.
