### ISSUE TITLE
The packaged PyPI package is only a source distribution - no wheels included

### ISSUE THREAD

**Issue by consideRatio** [tomplus/kubernetes_asyncio#201]
I saw that PyPI only includes a source distribution of this package, can we make it provide a wheel as well?

Here is an example on how to go about this using the `build` package as common nowdays instead of the old `python setup.py bdist_wheel`: https://github.com/jupyterhub/batchspawner/blob/master/.github/workflows/python-publish.yml.

For more details on wheels, see https://realpython.com/python-wheels/.

---

The reason I'm hoping for this, is that when I build kubernetes_asyncio from source in a memory constrained situation, i often crash with out of memory. I have not verified this would be resolved by having a wheel, but I think its a good practice that can't hurt.

![image](https://user-images.githubusercontent.com/3837114/163654098-6d79cc9a-f502-405c-b3f4-ce902f1138b6.png)
([Image from this workflow run](https://github.com/dask/dask-gateway/runs/6044075710?check_suite_focus=true))

**Comment by tomplus** [comment]
Definitely it's worth to do it.

**Comment by tomplus** [comment]
I've prepared and uploaded the wheel for version 22.6.4

**Comment by consideRatio** [comment]
@tomplus :tada: wieee thank you for your attention and care of this project!!

**Comment by consideRatio** [comment]
Would you like a PR with automation to do it in a GitHub Workflow?

**Comment by tomplus** [comment]
Yes, it would be nice. Thanks in advance.
