### ISSUE TITLE
Refresh service account token periodically

### ISSUE THREAD

**Issue by kafonek** [tomplus/kubernetes_asyncio#207]
Thank you for working on this project, I appreciate using `kubernetes_asyncio.py`.  

When using Python to talk to the Kubernetes API from within a Pod/container, `kubernetes.py` will periodically refresh/reload the service account token it is using, per https://github.com/kubernetes-client/python/issues/741 (closed by https://github.com/kubernetes-client/python-base/pull/250). Their original use case was for short-lived IAM credentials, but the issue is in focus again with warnings coming up in the Amazon EKS 1.21 and 1.22 release notes (https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html).

`kubernetes_asyncio.py` has some support for refreshing tokens but I believe it's only relevant to GCP tokens, not k8s service account tokens (https://github.com/tomplus/kubernetes_asyncio/pull/26). 

I have to admit I don't understand the nuances of how code is generated or customized in either project but I believe the main difference is in `config/kube_config.py` `KubeConfigLoader._set_config`
 - `kubernetes.py`  https://github.com/kubernetes-client/python-base/blob/master/config/kube_config.py#L568
 - `kubernetes_asyncio.py` https://github.com/tomplus/kubernetes_asyncio/blob/master/kubernetes_asyncio/config/kube_config.py#L367

**Comment by tomplus** [comment]
Thanks for kind words :) 

I know that one of the contributor is working on it here https://github.com/tomplus/kubernetes_asyncio/pull/205 I'm sure that it will be resolved soon.

**Comment by tomplus** [comment]
It's released in v22.6.5.
