### ISSUE TITLE
Consider moving this repo to https://github.com/aio-libs

### ISSUE THREAD

**Issue by olitheolix** [tomplus/kubernetes_asyncio#21]
This repository is difficult to find even if you know it exists. I think this is a pity because async support is a useful feature for a Kubernetes client library.

Therefore, would it make sense to move this repo into the [aio-libs](https://github.com/aio-libs) fold to give it more visibility and traction? Maybe also rename it to `aiokubernetes` for consistency with how many other popular async libraries are named?

**Comment by tomplus** [comment]
Sounds good but ... this library is a kind of extension of the official library (https://github.com/kubernetes-client/python). My plan is to show that it works, it's needed and eventually move this to https://github.com/kubernetes-client/ as a officially supported asynchronous version of python client.

If it doesn't happen I will follow your suggestion. Thanks.

**Comment by olitheolix** [comment]
Fair enough. Once you merge #22 and release a new version on PyPi I will deploy it for non-critical parts in our production systems to see how it fares when running for prolonged time periods. Thank you for making this library!
