### ISSUE TITLE
watch.stream no longer works with apis with follow kwarg

### ISSUE THREAD

**Issue by mcreng** [tomplus/kubernetes_asyncio#215]
This is a regression of #98, possibly coming from commit 2d0452d52, which changed the docstring of the methods from

```
:param bool follow: Follow the log stream of the pod. Defaults to false.
```

to

```
:param follow: Follow the log stream of the pod. Defaults to false.
:type follow: bool
```

causing

https://github.com/tomplus/kubernetes_asyncio/blob/65ce783fc3f015f9e464a90c028b902b58023c9b/kubernetes_asyncio/watch/watch.py#L24

and

https://github.com/tomplus/kubernetes_asyncio/blob/65ce783fc3f015f9e464a90c028b902b58023c9b/kubernetes_asyncio/watch/watch.py#L68-L72

to not work correctly.

@tomplus if you agree, we may do:
```diff
- PYDOC_FOLLOW_PARAM = ":param bool follow:" 
+ PYDOC_FOLLOW_PARAM = ":param follow:" 
```

**Comment by tomplus** [comment]
Good point. Thanks for your investigation. Could you send a PR to fix it?
