### ISSUE TITLE
Watch.stream() is not setting follow param for read_namespaced_pod_log

### ISSUE THREAD

**Issue by murali038** [tomplus/kubernetes_asyncio#227]
As part of API K8s v23.6.0 #211, the documentation has been updated and as per latest docstring of `read_namespaced_pod_log`

```
        :param follow: Follow the log stream of the pod. Defaults to false.
        :type follow: bool
```
but the global variable PYDOC_FOLLOW_PARAM is still set as `:param bool follow:` which needs updation

**Comment by murali038** [comment]
Sorry my bad my venv had older version installed. i didn't realize that. this is fixed as part of #216 . Sorry for the confusion. i will close it

**Comment by tomplus** [comment]
No worries! By the way, thanks for your engagement in the library.

**Comment by murali038** [comment]
Thank you so much Tom! so stupid of myself
--Murali
    On Saturday, November 5, 2022 at 06:43:27 PM EDT, Tomasz Prus ***@***.***> wrote:  
 
 


No worries! By the way, thanks for your engagement in the library.
