### ISSUE TITLE
Is there a way to change response content type?

### ISSUE THREAD

**Issue by ggree1** [tomplus/kubernetes_asyncio#237]
Hi,
Thanks for a great work.

I have a question.
How can I get pod detail for "application/yaml" content type?

I did like below but it always return json response cause in the source code, I couldn't find _content_type parameter does something.
Am I missing something?

`
v1.read_namespaced_pod_with_http_info(namespace=namespace, name=pod, _content_type="application/yaml")
`

**Comment by tomplus** [comment]
Hi, thanks for kind words.

Parameter _content_type is ignored and it's not possible to query APIServer to return yaml response in this library. However you can get a raw json reponse and try to convert it to yaml:

```
ret = await v1.read_namespaced_pod_with_http_info(namespace=namespace, name=pod, _preload_content=False)
json_data = await ret.content.read()
data = json.loads(json_data)
yaml_data = yaml.dump(data)
```
Does it work for you?

**Comment by ggree1** [comment]
Thanks for the answer.
I already solved problem like that. 
Is there any reason why that content type option being ignored?

**Comment by tomplus** [comment]
I think, it's just not implemented, the goal is to make a request and parse its response to create a python object.
