### ISSUE TITLE
Slow deepcopy

### ISSUE THREAD

**Issue by nosammai** [tomplus/kubernetes_asyncio#247]
Hello!

I have been running into some issues with CPU usage on my app that is doing some big/busy watches. I ran a profile and noticed that the deepcopy of the Configuration object in the openapi generated client is taking up the majority of the CPU time, as well as the rebuilding of the loggers that it subsequently triggers.

I tested disabling the copy of the Configuration by replacing [this line](https://github.com/kubernetes-client/python/blob/master/kubernetes/client/configuration.py#L210) with `return cls._default`, and it reduced the startup time of my application by about 7-10x. I have no idea what the ramifications of not copying that object are, but it _seems_ to still be working okay so far.

I'm curious if anyone else has run into these perf issues. I'm not sure I am knowledgeable enough to produce an actual fix for this, but was curious of the ramifications of not making that copy. It seems like most of the stuff in that Configuration object is related to the endpoint being connected to, so I'm wondering if it needs to be copied if my application is only connecting to a single kubernetes cluster?

Thanks!

**Comment by tomplus** [comment]
Hello @nosammai 

Thanks for reporting this issue and your investigation. It looks like you hit the same issue which exists in the synchronous client: https://github.com/kubernetes-client/python/issues/1921

You can use your workaround, it safe for me too.
The final solution is upgrading the generator to the next version which I'm working on now.

**Comment by tomplus** [comment]
I agree, let's keep it open.

**Comment by tomplus** [comment]
As I decided [not to upgrade the generator](https://github.com/tomplus/kubernetes_asyncio/issues/293) for now so I've applied a patch for it. It'll be available in the next release.
