### ISSUE TITLE
add config.load_config() support

### ISSUE THREAD

**Issue by abi-jey** [tomplus/kubernetes_asyncio#249]
Hi all, I think it would be useful to have support for simple load_config as implemented [here](https://github.com/kubernetes-client/python/blob/release-26.0/kubernetes/base/config/__init__.py), can someone give me feedback if this would be possible?

**Comment by tomplus** [comment]
Yes, it should be added. Would you like to work on it?

**Comment by naufalafif** [comment]
i don't think that's necessary. that's basically what `config.load_kube_config()` does.

code [here](https://github.com/kubernetes-client/python/blob/release-26.0/kubernetes/base/config/__init__.py) does the same thing, it's just wrapped by another class, you can check function `load_kube_config` inside it 

@realabja

**Comment by realabja** [comment]
@naufalafif, I think the difference is that load  config first tries to load from config and if there's none than it tries to creat config from pod configuration, which is way you would need to call manually in kubernetes_asyncio.

I think I will try to make pr and sumerise it there, but basically cluster user and service account should be able to call the same function to initialize configuration

**Comment by naufalafif** [comment]
i see, looks good

**Comment by james-mchugh** [comment]
I'm glad to hear I wasn't the only one looking for this function, but I am a bit surprised that no one beat me to the punch. It was a pretty simple copy and paste from the  https://github.com/kubernetes-client/python repo. I've opened up a PR for it, please let me know if you want me to make updates! #331
