### ISSUE TITLE
unwanted log output when using own logger

### ISSUE THREAD

**Issue by mpw96** [tomplus/kubernetes_asyncio#263]
Please see this example program:
```python
import asyncio
import logging
import sys

import kubernetes_asyncio

logger_name = sys.argv[1]
print(f"logger name will be '{logger_name}'.")

my_logger = logging.getLogger(logger_name)
my_logger.setLevel(logging.INFO)
my_logger.addHandler(logging.StreamHandler())


async def main():
    await kubernetes_asyncio.config.load_kube_config(config_file="/some-kubeconfig.yaml", context=None)
    my_logger.info("some text")


asyncio.run(main())
```

It creates a logger with the passed name and adds a simple handler to write the messages to the console.
When I pass the logger name `root` the output is this as expected:
```> python3 test_logging.py root
logger name will be 'root'.
some text
```

When I pass some other logger name the output is this:
```> python3 test_logging.py other
logger name will be 'other'.
some text
INFO:other:some text
```

Please note the last line of the output. I cannot explain where it comes from. When you comment out the line that starts with `await kubernetes_asyncio.config...` this extra line is not written. So IMO the `load_kube_config` seems to be causing it. Would you be able to fix this?

Python 3.9.15
kubernetes_asyncio 24.2.2

**Comment by tomplus** [comment]
Thanks for reporting the issue.
The problem is inside the kube_config.py, there are modul-level calls from logging, which use the root logger and reconfigure your logger too. I'll fix it in the new release.
