### ISSUE TITLE
Client doesn't honor `tls-server-name` setting in kubeconfig

### ISSUE THREAD

**Issue by multani** [tomplus/kubernetes_asyncio#267]
If a Kubernetes configuration file proposes the `tls-server-name` option, the asyncio client should configure the underlying HTTP library with this particular option.

See the upstream client issue about this: https://github.com/kubernetes-client/python/pull/1933

**Comment by multani** [comment]
I tried to look in the underlying aiohttp library to see how that could be configured, but I couldn't find the right option there :/

**Comment by multani** [comment]
It's currently blocked by aiohttp's lack of custom SNI support: https://github.com/aio-libs/aiohttp/issues/7114

**Comment by multani** [comment]
I created a pull request on aiohttp to add the missing feature: https://github.com/aio-libs/aiohttp/pull/7541

**Comment by tomplus** [comment]
@multani Thanks for you investigation!
