### ISSUE TITLE
Publish documentation

### ISSUE THREAD

**Issue by multani** [tomplus/kubernetes_asyncio#275]
The original Kubernetes client's documentation website is not great:

* https://kubernetes.readthedocs.io/en/latest/kubernetes.html#subpackages is mostly about tests (not super interesting for the documentation)
* All the modules are empty

Perhaps this module could be a bit better on that aspect :)

Would it be possible to publish the documentation for the asyncio variant on Read The Docs or some place similar?

**Comment by multani** [comment]
I would be interested to help move that forward, if there's some interest for this :+1:

**Comment by tomplus** [comment]
I did it some time ago, please take a look: https://kubernetes-asyncio.readthedocs.io/

**Comment by multani** [comment]
Ohhhh, that's great :bow: 

Can this be added in the README and/or the repository homepage URL? I totally missed this and this is great to have!
