### ISSUE TITLE
Add example for using the exec endpoint with stdin

### ISSUE THREAD

**Issue by philipsd6** [tomplus/kubernetes_asyncio#290]
As noted in #174, the synchronous version of this package has the [pod_exec.py](https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py) example, but only the non-interactive part of that is re-implemented in [examples/example3.py](https://github.com/tomplus/kubernetes_asyncio/blob/7d4357158937eae99437a27257c807dcf0df3f9b/examples/example3.py#L37). 

Is it possible to implement the interactive version with this library as well? My use case is to start `psql` in the container and execute various ddl statements from an operator (based on kopf) and emit the responses.

**Comment by tomplus** [comment]
Sure, it's possible but it has to be implemented first https://github.com/tomplus/kubernetes_asyncio/issues/12

**Comment by herman-ai** [comment]
@tomplus is #12 being actively worked on? I would also like this feature for my project.

**Comment by tomplus** [comment]
@herman-ai I'm not working on it right now, feel free to contribute if you want.
