### ISSUE TITLE
policy_v1beta1_api is not added in client package

### ISSUE THREAD

**Issue by haseungyeon** [tomplus/kubernetes_asyncio#305]
Other modules are imported in kubernetes_asyncio.client package, so users can access those modules by using paragraph `from kubernetes_asyncio.client import SomeK8sModule`.
But policy_v1beta1_api is not imported in kubernetes_asyncio.client package(__init__.py).
Is it omitted intentionally?

**Comment by tomplus** [comment]
Thanks for reporting the issue. It looks like this module should be removed as it's replaced by policy_v1_api.py (ref: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125).

If you need to use a beta version of this API you have to use an older version of this library (<=v24.2.3).

**Comment by haseungyeon** [comment]
Thank you for replying. I brought up this issue because there weren't pod_security_policy kinds of functions in policy_v1_api module, yet it was founded in policy_v1beta1_api. Will it be added in future kubernetes_asyncio version?

**Comment by tomplus** [comment]
The same situation, it's removed and won't be added to the library: https://kubernetes.io/docs/concepts/security/pod-security-policy/

**Comment by haseungyeon** [comment]
Thank for the explanation
