### ISSUE TITLE
Kube API has volume.read_only flag, but V1Volume has no

### ISSUE THREAD

**Issue by skabbit** [tomplus/kubernetes_asyncio#312]
By checking Kube API we could find the `readOnly` attribute both for `volumes` and `volume_mounts`: https://kubernetes.io/docs/concepts/storage/volumes/

But https://github.com/tomplus/kubernetes_asyncio/blob/c2c8933f29eee2c09d1be442e0b1d88a0ff39056/kubernetes_asyncio/client/models/v1_volume.py#L24 `V1Volume` class has no this attribute.

**Comment by tomplus** [comment]
For volume such attribute also exists but it's on vendor/type level, for example: 

https://github.com/tomplus/kubernetes_asyncio/blob/master/kubernetes_asyncio/client/models/v1_nfs_volume_source.py#L24

**Comment by tomplus** [comment]
Feel free to reopen if I can help in any way.
