### ISSUE TITLE
setuptools is erroneously declared as a runtime dependency

### ISSUE THREAD

**Issue by vilmosmartinek** [tomplus/kubernetes_asyncio#315]
The code base does not appear to use `setuptools` nor `pkg_resources`:

```
.../kubernetes_asyncio
> rg "pkg_resources"

.../kubernetes_asyncio
> rg "setuptools"
requirements.txt
4:setuptools>=21.0.0  # PSF/ZPL

setup.py
15:from setuptools import setup
27:# prerequisite: setuptools
28:# http://pypi.python.org/pypi/setuptools

doc/requirements.txt
5:setuptools>=21.0.0  # PSF/ZPL

kubernetes_asyncio/README.md
31:Install via [Setuptools](http://pypi.python.org/pypi/setuptools).
```

---

Please note that this same exact issue was reported and fixed in the "sister project" `kubernetes-client/python` (see [issue](https://github.com/kubernetes-client/python/issues/2021) and [pull request](https://github.com/kubernetes-client/python/pull/2022)).

**Comment by tomplus** [comment]
Sure, I'll do it soon.

**Comment by tomplus** [comment]
The version 29.0.1 has just been released, enjoy ;)
