### ISSUE TITLE
aiohttp client constructor is non-functional if verify_ssl=False is used

### ISSUE THREAD

**Issue by bpicolo** [tomplus/kubernetes_asyncio#32]
Currently the library passes both verify_ssl and ssl_context to the [TCPConnector](https://github.com/tomplus/kubernetes_asyncio/blob/master/kubernetes_asyncio/client/rest.py#L67), but the TCPConnector in recent aiohttp versions does not support having both.

```
ValueError: verify_ssl, ssl_context, fingerprint and ssl parameters are mutually exclusive
```

**Comment by tomplus** [comment]
I can confirm it - aiohttp >= 3.x has different and not compatible SSL parameters. As a workaround please use aiohttp==2.3.10

Thanks.

**Comment by bpicolo** [comment]
@tomplus  actually busted in 2.3.10 as well. Seems there's no valid version given the current pin

**Comment by tomplus** [comment]
You are right, 2.3.10 also has a similar constrain :( so now it's impossible to connect to a cluster with disabled ssl verification.

**Comment by tomplus** [comment]
@bpicolo the latest version contains your fix, thanks.
