### ISSUE TITLE
cannot retrieve the command exit code after a pod exec

### ISSUE THREAD

**Issue by olivier-matz-6wind** [tomplus/kubernetes_asyncio#322]
Hi,

I'm doing a pod exec using `client.CoreV1Api(WsApiClient()).connect_get_namespaced_pod_exec()`, very similar to what is done in the `pod_exec.py` example. I would like to get the command exit code but it seems this is not possible yet.

I have a draft patch that updates `kubernetes_asyncio/stream/ws_client.py` to store the content of `ERROR_CHANNEL` into a new field of the `WsApiClient`. This field can later be retrieved by the user.

```
--- a/kubernetes_asyncio/stream/ws_client.py
+++ b/kubernetes_asyncio/stream/ws_client.py
@@ -53,6 +53,7 @@ class WsApiClient(ApiClient):
                  cookie=None, pool_threads=1, heartbeat=None):
         super().__init__(configuration, header_name, header_value, cookie, pool_threads)
         self.heartbeat = heartbeat
+        self.error_data = None
 
     async def request(self, method, url, query_params=None, headers=None,
                       post_params=None, body=None, _preload_content=True,
@@ -82,6 +83,7 @@ class WsApiClient(ApiClient):
         if _preload_content:
 
             resp_all = ''
+            error_data = ''
             async with self.rest_client.pool_manager.ws_connect(url, headers=headers, heartbeat=self.heartbeat) as ws:
                 async for msg in ws:
                     msg = msg.data.decode('utf-8')
@@ -91,6 +93,11 @@ class WsApiClient(ApiClient):
                         if data:
                             if channel in [STDOUT_CHANNEL, STDERR_CHANNEL]:
                                 resp_all += data
+                            elif channel == ERROR_CHANNEL:
+                                error_data += data
+
+            if error_data:
+                self.error_data = error_data
 
             return WsResponse(200, resp_all.encode('utf-8'))
 ```

On success, `error_data` looks like this: `{"metadata":{},"status":"Success"}`.
On error, it looks like this: `{"metadata":{},"status":"Failure","message":"command terminated with non-zero exit code: error executing command [/bin/false], exit code 1","reason":"NonZeroExitCode","details":{"causes":[{"reason":"ExitCode","message":"1"}]}}`

Is it something that would make sense? If yes, I can submit a PR, otherwise do you have an alternative way of retrieving the exit code?

Thanks!

**Comment by olivier-matz-6wind** [comment]
I just realized I can set _preload_content to False, and do the send/recv by myself. So, I'm not sure this is needed after all. Should I add an example instead?

**Comment by tomplus** [comment]
The current implementation is very simply so I'm glad that you want to work on it :+1:  
You can take a look at [the official client](https://github.com/kubernetes-client/python/blob/master/kubernetes/base/stream/ws_client.py) and try to use the same public names eg. `returncode` property.
