### ISSUE TITLE
dynamic client failure when resource name has >2 parts

### ISSUE THREAD

**Issue by edwinpjacques** [tomplus/kubernetes_asyncio#342]
While using the dynamic client in an OpenShift environment, Discoverer.get_resources_for_api_version failed as follows:

```python
  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/dynamic/discovery.py", line 193, in get_resources_for_api_version

    resource, name = subresource['name'].split('/')

ValueError: too many values to unpack (expected 2)
```

The problematic resource was 'virtualmachineinstances/sev/fetchcertchain'.

Need to modify the code to make it more robust to handle such situations.

**Comment by edwinpjacques** [comment]
Hi @tomplus thanks for accepting my change! Just curious when it might get published to pypi? Thanks!

**Comment by tomplus** [comment]
@edwinpjacques The version v31.1.1 with your fix has been released. Thank you.
