### ISSUE TITLE
ApiClient creates new threadpool with number of active threads even though it isn't used

### ISSUE THREAD

**Issue by yuvipanda** [tomplus/kubernetes_asyncio#52]
In https://github.com/tomplus/kubernetes_asyncio/blob/master/kubernetes_asyncio/client/api_client.py#L69, a new ThreadPool is created per ApiClient. A lot of other objects (such as Watch) create an ApiClient per use, leading to lots of ThreadPools being created. ThreadPools aren't free - on my machine, merely instantiating a ThreadPool object (similar to what's happening here) starts *8* threads.

Very soon this becomes too many threads, and CPU usage / time for everything shoots up way high - bringing everything else to a halt.

In this client, the ThreadPool shouldn't be used at all, so we should remove it.

**Comment by yuvipanda** [comment]
Also, <3 thank you very much for this library!

**Comment by tomplus** [comment]
@yuvipanda Thanks. I'm happy to see that this library is useful for you.

You are right, in an asynchronous world these threads become obsolete but I keep it for compatibility reasons. I can port this https://github.com/swagger-api/swagger-codegen/pull/8061 - so the thread pool will be created on demand (probably never). WDYT?

**Comment by yuvipanda** [comment]
@tomplus yes, that sounds awesome :) would be lovely to renew push to get that merged too.

**Comment by tomplus** [comment]
It's been fixed in the latest version - v8.0.1.
