### ISSUE TITLE
Documentation on regenerating client

### ISSUE THREAD

**Issue by yuvipanda** [tomplus/kubernetes_asyncio#55]
I haven't quite found good docs on how to regenerate the client. Would you be able to point me to them, and/or put links in a CONTRIBUTING.md file?

**Comment by tomplus** [comment]
`CONTRIBUTING.md` was copied from the official repo. I'm afraid that the regenerating process are not described. I use this script https://github.com/tomplus/kubernetes_asyncio/blob/master/scripts/update-client.sh and it works quite nicely:

I'll update it soon.
