### ISSUE TITLE
Use of ssl_context= keyword raises DeprecationWarnings

### ISSUE THREAD

**Issue by mrocklin** [tomplus/kubernetes_asyncio#59]
I get the following deprecation warning when using this library.  

```python
lib/python3.6/site-packages/kubernetes_asyncio/client/rest.py:73: DeprecationWarning: ssl_context is deprecated, use ssl=context instead
    ssl_context=ssl_context
```

Swapping out `ssl_context=` for `ssl=` works fine when I apply the change locally.  However I'm not sure how best to enact change in this repository, given that parts (all?) of it is generated.  

cc @yuvipanda

**Comment by tomplus** [comment]
Yes, this part is generated by swagger-codegen. Now I'm working on switching to the openapi-generator (#58). It's fixed there in the beta release so this warning will be removed eventually.

**Comment by tomplus** [comment]
It's been fixed in the version v9.0.0.

**Comment by mrocklin** [comment]
Thanks!

**Comment by mickours** [comment]
The problem is still present in the current version (10.0.1):
```
kubernetes_asyncio/client/rest.py:69: DeprecationWarning: ssl_context is deprecated, use ssl=context instead
    ssl_context=ssl_context
```

**Comment by tomplus** [comment]
@mickours could you check the version of aiohttp? The latest version of the library can print such warnings: https://github.com/tomplus/kubernetes_asyncio/issues/87 Thanks.

**Comment by mickours** [comment]
Thanks for the quick answer!

I'm using aiohttp 3.5.4

It seems to come from this line:
https://github.com/tomplus/kubernetes_asyncio/blob/master/kubernetes_asyncio/client/rest.py#L69

**Comment by tomplus** [comment]
Thanks, confirmed, reopen the issue.

**Comment by tomplus** [comment]
It's fixed in the latest version of the library.

**Comment by mrocklin** [comment]
I'm glad to hear it!  Thank you for tracking this @tomplus .

**Comment by mickours** [comment]
Thanks a lot! 👍
