### ISSUE TITLE
field_selector for custom objects missing

### ISSUE THREAD

**Issue by HaraldGustafsson** [tomplus/kubernetes_asyncio#62]
Noticed that the field_selector parameter is missing for listing custom objects `list_cluster_custom_object` and `list_namespaced_custom_object` in `custom_objects_api`. See this issue for when it was added to Kubernetes.
[https://github.com/kubernetes/kubernetes/issues/51046](https://github.com/kubernetes/kubernetes/issues/51046)

It should support field selector for name and namespace (potentially more later)

Don't know if it is missing from all OpenAPI generated clients.

It works from kubectl:
`kubectl -v=7 get customobjname --field-selector "metadata.name=myname"  -o yaml`
lists CRDs of customobjname kind.

**Comment by tomplus** [comment]
Thanks for spotting this. All clients are affected and I've just added a PR https://github.com/kubernetes-client/gen/pull/106 to add the parameter.

**Comment by tomplus** [comment]
It's been fixed in the version v9.0.0.
