### ISSUE TITLE
Breaking change: "body" becomes a keyword-only argument in delete operations since v9.0.0

### ISSUE THREAD

**Issue by hubo1016** [tomplus/kubernetes_asyncio#65]
Not a big deal, just reporting.

Users must modify
`delete_xxx(name, namespace, options)`
to
`delete_xxx(name, namespace, body=options)`
in v9.0.0

**Comment by tomplus** [comment]
@hubo1016 Thanks for spotting this.

This difference was introduced in the official spec: https://github.com/kubernetes/kubernetes/pull/70032

**Comment by tomplus** [comment]
I've added a notice about it to the changelog file.
