### ISSUE TITLE
RuntimeError: Event loop is closed in __del__ of rest client

### ISSUE THREAD

**Issue by mickours** [tomplus/kubernetes_asyncio#67]
When running a REST client with 
`asyncio.wait(tasks, return_when="FIRST_EXCEPTION")`
I get an unexpected exception the `__del__` method of the REST client that makes my program fails.

The exception is the pool manager closing  on a closed loop. Here is a curated stack trace:
 ```
Exception ignored in: <bound method RESTClientObject.__del__ of <kubernetes_asyncio.client.rest.RESTClientObject object at 0x7f0edd67b198>>
File "kubernetes_asyncio/client/rest.py", line 84, in __del__
    asyncio.ensure_future(self.pool_manager.close())                                                                                                                                          
RuntimeError: Event loop is closed
```
Seems related to #25 but I'm not sure how I can workaround this, any insight?

**Comment by tomplus** [comment]
I can't reproduce this error. Can you provide more details? Does it occur when your program is exiting?

**Comment by mickours** [comment]
Sorry about the lack of details, I wrote this too quickly... I'll give you a minimum working example on monday with more details.

**Comment by mickours** [comment]
Seems to be a transient failure due to my flaky network, sorry about that.
Thank you for your time, I'll reopen this if I found a reproducible error case.

**Comment by tomplus** [comment]
No problem. I'm glad to hear that it works.
