### ISSUE TITLE
RESTClientObject maxsize

### ISSUE THREAD

**Issue by HaraldGustafsson** [tomplus/kubernetes_asyncio#74]
Hi,

I finally realized what the issue was in my program using kubernetes asyncio that made it have a slow progress. It is the maxsize in RESTClientObject is set to only 4. In some scenarios I use the same client for many watch operations, but they would be competing over the 4 available connections. Could we either remove the limit (default is 100 in aiohttp) or make it possible to set in the kubernetes Configuration class. The pool based ones can set the pool size, seems like we could reuse that with a more generic name.

**Comment by tomplus** [comment]
Based on your idea, in the latest version of the library the limit max-size=4 has been removed and default aiohttp is taken. It can be also configured from the Configuration class.
Thanks for reporting this issue.
