### ISSUE TITLE
No async utils.create_from_yaml() alternative

### ISSUE THREAD

**Issue by PidgeyBE** [tomplus/kubernetes_asyncio#75]
Hey!

I was trying to convert my python code using the `kubernetes` package to async using the `kubernetes-asyncio` package. The only functionality I'm missing is the `kubernetes.utils.create_from_yaml()`. It doesn't work with asynchronous clients.

I'm talking about this: https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/create_from_yaml.py

I'll try to create a PR.

**Comment by PidgeyBE** [comment]
https://github.com/tomplus/kubernetes_asyncio/pull/76

**Comment by tomplus** [comment]
@PidgeyBE thanks for working on this!

**Comment by PidgeyBE** [comment]
You're welcome, I'll try to make the changes you've requested!

**Comment by tomplus** [comment]
The PR is already merged, thanks again.

**Comment by PidgeyBE** [comment]
Is there a new release with this enhancement coming any time soon?

**Comment by tomplus** [comment]
Yes, I'm going to release the new version in this week.

**Comment by tomplus** [comment]
@PidgeyBE I've just release the library. Thank you for your contribution.
