### ISSUE TITLE
Watching with specified resource_version

### ISSUE THREAD

**Issue by TrueBrain** [tomplus/kubernetes_asyncio#77]
Currently when you start a `stream()` (on a `Watch()`) with a specific `resource_version`, the retry after a timeout fails if no new events arrived.

This has been solved in `kubernetes-client` with:
https://github.com/kubernetes-client/python-base/commit/2d69e89dab7134186cbcdaf82381ab6295c6c394

Having this added to `kubernetes_asyncio` would be really useful, although a workaround is also pretty simple (create the `Watch()` object and set `resource_version` there too before calling `stream()`). But this is a bit of a hack ;)

I tried to backport this myself, but got hopefully lost in the test case.

**Comment by tomplus** [comment]
@TrueBrain Thanks for spotting this. Please try to add it if you can. I'll help you with tests.
