### ISSUE TITLE
Request method change in POST queries

### ISSUE THREAD

**Issue by xxxbobrxxx** [tomplus/kubernetes_asyncio#78]
Hi!
Methods like CoreV1Api.connect_post_namespaced_service_proxy which must produce POST requests in fact produces 2 requests:

- POST to .../proxy Kubernetes API returns 301
- GET to .../proxy/

This caused by aiohttp behaviour, see links:

- https://github.com/aio-libs/aiohttp/issues/3578
- https://stackoverflow.com/questions/42136829/whats-the-difference-between-http-301-and-308-status-codes

It makes this methods unusable.

**Comment by tomplus** [comment]
@xxxbobrxxx Thanks for opening the issue.

It looks like the K8s API server should return 308 in this case. Could you report this in the official repository?

As a workaround you can try to use the method `connect_post_namespaced_pod_proxy_with_path` with `path=""`. It'll send a request with the trailing slash.

BTW, I'm curious what you want to do. This part of K8s api is not well described, is it something related to port-forwarding? Thanks.

**Comment by xxxbobrxxx** [comment]
For your interest:
I develop software which discovers service resources and send data to it. Do debug it outside Kubernetes cluster easier to develop layer to send requests using Kubernetes API.
Also, CoreV1Api.connect_post_namespaced_service_proxy* methods does not allow to send POST data, but Kubernetes API can accept it because /proxy API url transparently resends requests to services.

**Comment by tomplus** [comment]
Please report this issue in the Kubernetes repository.
